### ISSUE TITLE
index_pi.js does not populate "elgfilepicker" "sdpi-file-info" label with already set payload setting text  when reopening PI

### ISSUE THREAD

**Issue by krabs-github** [elgatosf/streamdeck-plugintemplate#11]
index_pi.js does not populate "elgfilepicker" "sdpi-file-info" label with already set payload setting text when reopening PI. It always returns to "no file....".
```
            <div class="sdpi-item" id="my_private_file_selector">
                <div class="sdpi-item-label">Background Image</div>
                <div class="sdpi-item-group file" id="filepickergroup">
                    <input class="sdpi-item-value" type="file" id="elgfilepicker" accept=".jpg, .jpeg, .png">
                    <label class="sdpi-file-info" for="elgfilepicker">no file...</label>
                    <label class="sdpi-file-label" for="elgfilepicker">Choose file...</label>
                 </div>
             </div>
```

**Comment by tiptronic** [comment]
elgfilepicker acts for type `file` not `text`... 

if you want to show a custom value you need to set it by yourself. But passing a `text` as file, would better fit into a regular `text` input field

**Comment by krabs-github** [comment]
Let me try to be more clear, It doesn't display the file the user has
chosen when returning to the PI.

**Comment by krabs-github** [comment]
Let me try to be more clear, It doesn't display the file the user has
chosen when returning to the PI.

In this screenshot the custom image is set from the file picker... it is set correctly and stays set correctly. However, when you reopen the PI screen this is what the user sees:

![elgfilepicker value](https://user-images.githubusercontent.com/78506543/147087581-fa779b19-0555-4f5b-86dd-c3e13209e97e.png)

In addition, Check boxes behave like this when returning the PI screen...
First time, no value set:

![checkbox in PI before leaving PI or changing the state of the checkbox](https://user-images.githubusercontent.com/78506543/147087986-0b8c39ee-dca9-4fd8-a11a-ac6764ac807e.png)

After clicking the checkbox and returning to the PI:
![checkbox after return to the PI screen](https://user-images.githubusercontent.com/78506543/147088045-78b67a48-a678-4dfa-acec-55ed8c578941.png)

Code being used in the PI from PI_Samples
```
             <div type="checkbox" class="sdpi-item" id="single-check">
                 <div class="sdpi-item-label">Test</div>
                 <div class="sdpi-item-value">
                     <div class="sdpi-item-child">
                         <input id="singlechk" type="checkbox" value="on">
                         <label for="singlechk" class="sdpi-item-label"><span></span>on</label>
                     </div>
                 </div>
```

**Comment by tiptronic** [comment]
First of all, please let me add: this is a template - only a starting-point, not a full-fledged plugin. It is meant just as a quick starter for your own plugins...

Since there's no file-inputs or checkboxes in the template, it seems you created some. Please take a look at the `PISamples` plugin how to do that.

Even if I create a checkbox in the template, I can't see the problem... 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/80752/147119990-d6dfa3de-2303-4cf9-8c2a-586e4529ad81.png">

The second problem has also nothing to do with the template... It seems you need to adjust the `id` of your `sdpi-item`....   (`id="something-else"` instead `id="single-check"`). There seem to be 2 different items with the same id in the DOM.
That might be the problem with the file-picker as well...

**Comment by krabs-github** [comment]
You should note in the description that somethings you say works, do not.
Don't worry, we will code it ourselves since you are incapable and don't
care.
