### ISSUE TITLE
Is there a way to get an image file from Property Inspector?

### ISSUE THREAD

**Issue by artrointel** [elgatosf/streamdeck-plugintemplate#7]
Is there a way to get an image file from Property Inspector?

I'm building a plugin that can be extremely customized by user in Property Inspector.
(I aim to upload your plugin market after done)
![Animation](https://user-images.githubusercontent.com/8336352/122140626-b7d41080-ce86-11eb-8ac6-349913f9561a.gif) 
currently I guess there is no way to get the user's image file input through the property inspector.
(I placed this avengers logo image manually in .sdPlugin.)

AFAIK, The PI which is written in javascript, there is no way to get such a user's local directory path of a file or its file by web security issue. (html input tag does not work in stream deck.)

I'm hoping to get a file from user with the plugin somehow.
Is there any way to make it?

**Comment by tiptronic** [comment]
@artrointel No - you can't get the image from a key. This is not necessarily a file anyway, because quite some plugins generate their images in code (e.g. on a Canvas).
From the Property Inspector you can get images to your plugin... see the [PISamples.sdPlugin](https://github.com/elgatosf/streamdeck-pisamples) for how to do it...

**Comment by artrointel** [comment]
I got a hint from the pisamples as you mentioned, and found the correct way;
decodeURIComponent(input.value.replace(/^C:\\fakepath\\/, ''));
that was what I'm looking for it. really thanks.
now it works.
